### PR TITLE
Add REST API Wrapper

### PR DESCRIPTION
**Pull request by vbe0201**
# Pull Request Template

Please try to complete the below as best as possible. Some of the fields
may not be necessary so feel free to add or edit as you see fit.

## Checklist

- [ ] There is an existing issue report for this PR.
- [ ] I have forked this project.
- [x] I have created a feature branch.
- [x] My changes have been committed.
- [x] I have pushed my changes to the branch.

## Title

Add support for REST API interaction.

## Description

This Pull Request adds support for interaction with the Discord REST API. It provides an interface for HTTP requests via [asks](https://github.com/theelous3/asks) that also parses responses, handles errors and rate limits and dynamically manages re-attempts on request failures caused by stupid network errors and internal server errors on Discord's side.

## New or Changed Features

* [x] Add enum for all endpoints that should be supported. No sketchy strings out of nowhere.

* [x] Add interface for HTTP requests that does
  * [x] perform the requests itself with a method provided by the enum for the endpoints.
  * [x] parse the HTTP status code to decide if a request was successful or not.
  * [x] dynamic error handling for erroneous cases.
  * [x] parsing the responses that can be either JSON, text (errors) or ``null`` (HTTP status code 204).
  * [x] handle rate limits provided by the response headers of API requests.

* [x] Wrapping the endpoints for providing factory methods for a higher-level API.

* [x] Caching so users can keep track of outgoing requests?

* [x] Unit tests.

* [x] Concise and informative documentation that fully covers the ``rest`` package.

### CODE REVIEW

**Comment by vbe0201** [comment]
Yet work in progress.

**Review by Not-Nik — APPROVED** [review]

**Comment by vbe0201** [comment]
All set. Ready to be merged.

**Review by Stupremee — APPROVED** [review]
Looks good

**Review by yk-sgr — APPROVED** [review]
Very gud

**Pull request merged**
